spring:
  application:
    name: user-service
  profiles:
    active: dev
  # Config Server 연결 제거 (시작 지연 원인일 수 있음)
  # config:
  #   import: optional:configserver:http://localhost:8888
  # Flyway 비활성화
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8090

# SpringDoc 설정 - 간단하고 안정적인 설정
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  packages-to-scan:
    - com.restaurant.user.presentation
    - com.restaurant.common.presentation

app:
  problem:
    base-url: https://test-api.restaurant.com/probs

# Outbox Polling configuration (Disabled for now)
outbox:
  polling:
    enabled: false
    fixed-delay: 5000 # Poll every 5 seconds (reduced frequency)
    batch-size: 10

# Logging 설정
logging:
  level:
    com.restaurant: INFO
    org.hibernate.SQL: DEBUG
    org.springdoc: DEBUG
    io.swagger: DEBUG
# --- Staging/Production Profile (별도 파일 또는 외부 설정 관리) ---
# 민감 정보(DB 비밀번호, API 키 등)는 환경 변수 또는 Secret Manager 사용
# 예시:
# spring.datasource.password: ${DB_PASSWORD}
# spring.kafka.properties.schema.registry.url: ${SCHEMA_REGISTRY_URL}
