springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  paths-to-match: /api/**
  packages-to-scan: com.restaurant.presentation
  cache:
    disabled: true

app:
  problem:
    base-url: https://restaurant.com/problems
