spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: outbox-producer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      compression-type: snappy
      max-in-flight-requests-per-connection: 1
      max-request-size: 1048576
      request-timeout-ms: 30000
      enable-idempotence: true
      properties:
        schema.registry.url: http://localhost:8081

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

outbox:
  polling:
    interval: 5000
    batch-size: 100
    max-retries: 3
