spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_inserts: true
        order_updates: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      compression-type: lz4
      delivery-timeout-ms: 120000
      request-timeout-ms: 30000
      max-block-ms: 60000
      properties:
        enable.idempotence: true
        isolation.level: read_committed

outbox:
  polling:
    batch-size: 100
    max-retries: 3
    pending-messages-interval: 5000 # 5 seconds
    failed-messages-interval: 60000 # 1 minute
